// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { PlayerRename } from '../client-event/player-rename.js';


export enum EventUnion {
  NONE = 0,
  PlayerRename = 1
}

export function unionToEventUnion(
  type: EventUnion,
  accessor: (obj:PlayerRename) => PlayerRename|null
): PlayerRename|null {
  switch(EventUnion[type]) {
    case 'NONE': return null; 
    case 'PlayerRename': return accessor(new PlayerRename())! as PlayerRename;
    default: return null;
  }
}

export function unionListToEventUnion(
  type: EventUnion, 
  accessor: (index: number, obj:PlayerRename) => PlayerRename|null, 
  index: number
): PlayerRename|null {
  switch(EventUnion[type]) {
    case 'NONE': return null; 
    case 'PlayerRename': return accessor(index, new PlayerRename())! as PlayerRename;
    default: return null;
  }
}
