// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { PlayerIncreaseScore } from './player-increase-score.js';
import { PlayerJoined } from './player-joined.js';
import { PlayerLeft } from './player-left.js';
import { PlayerRename } from './player-rename.js';


export enum EventUnion {
  NONE = 0,
  PlayerJoined = 1,
  PlayerLeft = 2,
  PlayerRename = 3,
  PlayerIncreaseScore = 4
}

export function unionToEventUnion(
  type: EventUnion,
  accessor: (obj:PlayerIncreaseScore|PlayerJoined|PlayerLeft|PlayerRename) => PlayerIncreaseScore|PlayerJoined|PlayerLeft|PlayerRename|null
): PlayerIncreaseScore|PlayerJoined|PlayerLeft|PlayerRename|null {
  switch(EventUnion[type]) {
    case 'NONE': return null; 
    case 'PlayerJoined': return accessor(new PlayerJoined())! as PlayerJoined;
    case 'PlayerLeft': return accessor(new PlayerLeft())! as PlayerLeft;
    case 'PlayerRename': return accessor(new PlayerRename())! as PlayerRename;
    case 'PlayerIncreaseScore': return accessor(new PlayerIncreaseScore())! as PlayerIncreaseScore;
    default: return null;
  }
}

export function unionListToEventUnion(
  type: EventUnion, 
  accessor: (index: number, obj:PlayerIncreaseScore|PlayerJoined|PlayerLeft|PlayerRename) => PlayerIncreaseScore|PlayerJoined|PlayerLeft|PlayerRename|null, 
  index: number
): PlayerIncreaseScore|PlayerJoined|PlayerLeft|PlayerRename|null {
  switch(EventUnion[type]) {
    case 'NONE': return null; 
    case 'PlayerJoined': return accessor(index, new PlayerJoined())! as PlayerJoined;
    case 'PlayerLeft': return accessor(index, new PlayerLeft())! as PlayerLeft;
    case 'PlayerRename': return accessor(index, new PlayerRename())! as PlayerRename;
    case 'PlayerIncreaseScore': return accessor(index, new PlayerIncreaseScore())! as PlayerIncreaseScore;
    default: return null;
  }
}
