[workspace]
members = ["drawduel_engine", "drawduel_wasm", "drawduel_server", "drawduel_scripts"]
resolver = "2"

# https://nnethercote.github.io/perf-book/build-configuration.html
[profile.release]
codegen-units = 1
lto = "fat"
strip = true
panic = "abort"
