// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class PlayerLeft {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PlayerLeft {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPlayerLeft(bb:flatbuffers.ByteBuffer, obj?:PlayerLeft):PlayerLeft {
  return (obj || new PlayerLeft()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPlayerLeft(bb:flatbuffers.ByteBuffer, obj?:PlayerLeft):PlayerLeft {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PlayerLeft()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startPlayerLeft(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(0, id, 0);
}

static endPlayerLeft(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPlayerLeft(builder:flatbuffers.Builder, id:number):flatbuffers.Offset {
  PlayerLeft.startPlayerLeft(builder);
  PlayerLeft.addId(builder, id);
  return PlayerLeft.endPlayerLeft(builder);
}
}
