[package]
name = "drawduel_engine"
version = "1.0.0"
authors = ["pretzelhammer <7769424+pretzelhammer@users.noreply.github.com>"]
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.84"
prost = "0.13.0"
serde = "1.0.217"
