// @generated
// This file is @generated by prost-build.
// GAME STATE

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GameState {
    #[prost(map="uint32, message", tag="1")]
    pub players: ::std::collections::HashMap<u32, Player>,
    #[prost(uint32, tag="2")]
    pub admin: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Player {
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(uint32, tag="3")]
    pub score: u32,
    #[prost(bool, tag="4")]
    pub connected: bool,
    #[prost(bool, tag="5")]
    pub ready: bool,
}
// EVENTS SERVER CAN SEND

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerEventSetGameState {
    #[prost(uint32, tag="1")]
    pub player_id: u32,
    #[prost(message, optional, tag="2")]
    pub game_state: ::core::option::Option<GameState>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerEventError {
    #[prost(enumeration="ErrorType", tag="1")]
    pub r#type: i32,
    #[prost(string, tag="2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerEventPlayerJoin {
    #[prost(uint32, tag="1")]
    pub id: u32,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ServerEventPlayerConnect {
    #[prost(uint32, tag="1")]
    pub id: u32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ServerEventPlayerLeave {
    #[prost(uint32, tag="1")]
    pub id: u32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ServerEventPlayerDisconnect {
    #[prost(uint32, tag="1")]
    pub id: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerEventPlayerRename {
    #[prost(uint32, tag="1")]
    pub id: u32,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ServerEventPlayerIncreaseScore {
    #[prost(uint32, tag="1")]
    pub id: u32,
    #[prost(uint32, tag="2")]
    pub score: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerEvent {
    #[prost(oneof="server_event::Type", tags="1, 2, 3, 4, 5, 6, 7, 8")]
    pub r#type: ::core::option::Option<server_event::Type>,
}
/// Nested message and enum types in `ServerEvent`.
pub mod server_event {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Type {
        #[prost(message, tag="1")]
        PlayerJoin(super::ServerEventPlayerJoin),
        #[prost(message, tag="2")]
        PlayerLeave(super::ServerEventPlayerLeave),
        #[prost(message, tag="3")]
        PlayerRename(super::ServerEventPlayerRename),
        #[prost(message, tag="4")]
        PlayerIncreaseScore(super::ServerEventPlayerIncreaseScore),
        #[prost(message, tag="5")]
        SetGameState(super::ServerEventSetGameState),
        #[prost(message, tag="6")]
        Error(super::ServerEventError),
        #[prost(message, tag="7")]
        PlayerConnect(super::ServerEventPlayerConnect),
        #[prost(message, tag="8")]
        PlayerDisconnect(super::ServerEventPlayerDisconnect),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerEvents {
    #[prost(message, repeated, tag="1")]
    pub events: ::prost::alloc::vec::Vec<ServerEvent>,
}
// EVENTS PLAYERS CAN SEND

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlayerEventRename {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PlayerEventIncreaseScore {
    #[prost(uint32, tag="1")]
    pub score: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlayerEvent {
    #[prost(oneof="player_event::Type", tags="1, 2")]
    pub r#type: ::core::option::Option<player_event::Type>,
}
/// Nested message and enum types in `PlayerEvent`.
pub mod player_event {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Type {
        #[prost(message, tag="1")]
        Rename(super::PlayerEventRename),
        #[prost(message, tag="2")]
        IncreaseScore(super::PlayerEventIncreaseScore),
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ErrorType {
    Unknown = 0,
    AlreadyConnected = 1,
    FullGame = 2,
}
impl ErrorType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "UNKNOWN",
            Self::AlreadyConnected => "ALREADY_CONNECTED",
            Self::FullGame => "FULL_GAME",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN" => Some(Self::Unknown),
            "ALREADY_CONNECTED" => Some(Self::AlreadyConnected),
            "FULL_GAME" => Some(Self::FullGame),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
